name: Compile pdf
on:
  push:
    branches:
      - dev
env:
  CV_TEX: cv.tex
  CV_PDF: cv.pdf
  CV_TEX_RU: cv.tex
  CV_PDF_RU: cv.pdf
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            - ${{ env.CV_TEX  }}
            - ${{ env.CV_TEX_RU  }}
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: | 
            - ${{ env.CV_PDF }}
            - ${{ env.CV_PDF_RU }}
